config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'visitors#index', as: :authenticated_root
    end
    root to: "devise/sessions#new"
  end

  resources :sightings do
    resources :blows
    resources :biopsies
    resources :feces
    resources :animal_sightings
  end
  resources :regions
  resources :sea_states
  resources :cloud_covers
  resources :vessels
  resources :modes
  resources :species
  resources :animals
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user && user.admin?
      can :manage, Animal
      can :manage, AnimalSighting
      can :manage, Biopsy
      can :manage, Blow
      can :manage, CloudCover
      can :manage, Fece
      can :manage, Mode
      can :manage, Region
      can :manage, SeaState
      can :manage, Sighting
      can :manage, Species
      can :manage, User
      can :manage, Vessel
    end
  end
end

app/models/animal.rb
class Animal < ActiveRecord::Base
  belongs_to :biopsy
  belongs_to :fece
  belongs_to :blow
  belongs_to :vessel
  belongs_to :species

  def to_s
    name
  end
end

app/models/animal_sighting.rb
class AnimalSighting < ActiveRecord::Base
  belongs_to :animal
  belongs_to :sighting
end

app/models/biopsy.rb
class Biopsy < ActiveRecord::Base
  belongs_to :sighting

  def to_s
    "#{tissue} - #{preservation} - #{purpose} - #{reaction}"
  end
end

app/models/blow.rb
class Blow < ActiveRecord::Base
  belongs_to :sighting
end

app/models/cloud_cover.rb
class CloudCover < ActiveRecord::Base
  def to_s
    name
  end
end

app/models/fece.rb
class Fece < ActiveRecord::Base
  belongs_to :sighting
end

app/models/mics_pix.rb
class MicsPix < ActiveRecord::Base
  establish_connection(:mics_pix)
  def self.table_name
    "whale"
  end
end

app/models/mode.rb
class Mode < ActiveRecord::Base
  def to_s
    name
  end
end

app/models/region.rb
class Region < ActiveRecord::Base
  def to_s
    name
  end
end

app/models/sea_state.rb
class SeaState < ActiveRecord::Base
  def to_s
    name
  end
end

app/models/sighting.rb
class Sighting < ActiveRecord::Base
  belongs_to :region
  belongs_to :vessel
  belongs_to :sea_state
  belongs_to :cloud_cover
  belongs_to :mode
  belongs_to :species

  has_many :biopsies
  has_many :feces
  has_many :blows
  has_many :animal_sightings
  has_many :animals, through: :animal_sightings

  def self.search(search)
    if search
      where(search.delete_if { |k,v| v.empty? })
    else
      all
    end
  end

  def to_s
    id.to_s
  end
end

app/models/species.rb
class Species < ActiveRecord::Base
  def to_s
    name
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vessel.rb
class Vessel < ActiveRecord::Base
  def to_s
    name
  end
end

app/controllers/animal_sightings_controller.rb
class AnimalSightingsController < InheritedResources::Base
  load_and_authorize_resource

  include SmartListing::Scaffold

  belongs_to :sighting

  def index
    smart_listing_create :animal_sightings, parent.animal_sightings, partial: "list"
  end

  def new
    @animal_sighting = AnimalSighting.new(sighting: @sighting)
    respond_to do |format|
      format.html { index }
      format.js { super }
    end
  end

  private

  def columns
    [:sighting_id, :animal_id]
  end
end

app/controllers/animals_controller.rb
class AnimalsController < InheritedResources::Base
  load_and_authorize_resource

  include SmartListing::Scaffold

  def index
    animals = Animal.includes(:species, :vessel).all
    smart_listing_create :animals, animals, partial: "animals/list"
  end

  private

  def columns
    [:number, :field_id, :pics_id, :position_in_group, :biopsy_id,
     :cow_calf, :first_sight, :time, :species_id, :vessel_id]
  end
end

app/controllers/blows_controller.rb
class BlowsController < InheritedResources::Base
  load_and_authorize_resource

  include SmartListing::Scaffold

  belongs_to :sighting

  def index
    smart_listing_create :blows, parent.blows, partial: "list"
  end

  def new
    @blow = Blow.new(sighting: @sighting)
    respond_to do |format|
      format.html { index }
      format.js { super }
    end
  end

  private

  def columns
    [:distance, :quality, :preservation, :behavior, :group_size, :comments,
     :sighting_id]
  end
end

app/controllers/feces_controller.rb
class FecesController < InheritedResources::Base
  load_and_authorize_resource

  include SmartListing::Scaffold

  belongs_to :sighting

  def index
    smart_listing_create :feces, parent.feces, partial: "list"
  end

  def new
    @fece = Fece.new(sighting: @sighting)
    respond_to do |format|
      format.html { index }
      format.js { super }
    end
  end

  private

  def columns
    [:mass, :color, :consistency, :preservation]
  end
end

app/controllers/modes_controller.rb
class ModesController < InheritedResources::Base
  load_and_authorize_resource

  include SmartListing::Scaffold
end

app/controllers/regions_controller.rb
class RegionsController < InheritedResources::Base
  load_and_authorize_resource

  include SmartListing::Scaffold
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_mics_pix(animal:)
    if animal.pics_id.present?
      link_to "MicsPix", MicsPixLinkCreator.new(animal: animal).call,
        target: '_blank'
    end
  end
end

app/views/animal_sightings/_form.html.slim
td colspan="3"
  = simple_form_for([parent, object],
    html: {class: 'form-horizontal' }, remote: true) do |f|
    .container
      .row
        = f.association :animal
    .control-group
      .controls
        = f.submit t('shared.submit'), class: 'btn btn-primary'
        button.btn.btn-link.cancel Annuler

app/views/animal_sightings/_item.html.slim
td
  = object.animal
td
  = object.sighting
td.actions
  = smart_listing_item_actions [ { name: :edit,
    url: edit_sighting_animal_sighting_path(parent, object) },
    { name: :destroy, url: sighting_animal_sighting_path(parent, object),
      confirmation: t('smart_listing.msgs.destroy_confirmation') }]

app/views/animal_sightings/_list.html.slim
h1 Animal Sightings
table.table.table-striped
  thead
    th animal
    th sighting
    th
  tbody
    - if smart_listing.empty?
      tr
        td
          = t('smart_listing.no_data')
    - else
      - smart_listing.collection.each do |object|
        tr.editable [data-id="#{object.id}"]
          = render "item", object: object
    = smart_listing.item_new link: new_sighting_animal_sighting_path
= smart_listing.paginate
= smart_listing.pagination_per_page_links

app/views/animal_sightings/index.html.slim
= smart_listing_render(:animal_sightings)

app/views/animal_sightings/index.js.erb
<%= smart_listing_update :animal_sightings %>

app/views/animal_sightings/new.html.slim
= smart_listing_render(:animal_sightings)
javascript:
  var smart_listing = $('#animal_sightings').smart_listing();
  smart_listing.new_item("#{j(render('form', object: resource))}");