config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'visitors#index', as: :authenticated_root
    end
    root to: "devise/sessions#new"
  end

  resources :sightings do
    resources :blows
    resources :biopsies
    resources :feces
    resources :animal_sightings
  end
  resources :regions
  resources :sea_states
  resources :cloud_covers
  resources :vessels
  resources :modes
  resources :species
  resources :animals
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user && user.admin?
      can :manage, Animal
      can :manage, AnimalSighting
      can :manage, Biopsy
      can :manage, Blow
      can :manage, CloudCover
      can :manage, Fece
      can :manage, Mode
      can :manage, Region
      can :manage, SeaState
      can :manage, Sighting
      can :manage, Species
      can :manage, User
      can :manage, Vessel
    end
  end
end

app/models/animal.rb
class Animal < ActiveRecord::Base
  belongs_to :biopsy
  belongs_to :fece
  belongs_to :blow
  belongs_to :vessel
  belongs_to :species

  def to_s
    name
  end
end

app/models/animal_sighting.rb
class AnimalSighting < ActiveRecord::Base
  belongs_to :animal
  belongs_to :sighting
end

app/models/biopsy.rb
class Biopsy < ActiveRecord::Base
  belongs_to :sighting

  def to_s
    "#{tissue} - #{preservation} - #{purpose} - #{reaction}"
  end
end

app/models/blow.rb
class Blow < ActiveRecord::Base
  belongs_to :sighting
end

app/models/cloud_cover.rb
class CloudCover < ActiveRecord::Base
  def to_s
    name
  end
end

app/models/fece.rb
class Fece < ActiveRecord::Base
  belongs_to :sighting
end

app/models/mics_pix.rb
class MicsPix < ActiveRecord::Base
  establish_connection(:mics_pix)
  def self.table_name
    "whale"
  end
end

app/models/mode.rb
class Mode < ActiveRecord::Base
  def to_s
    name
  end
end

app/models/region.rb
class Region < ActiveRecord::Base
  def to_s
    name
  end
end

app/models/sea_state.rb
class SeaState < ActiveRecord::Base
  def to_s
    name
  end
end

app/models/sighting.rb
class Sighting < ActiveRecord::Base
  belongs_to :region
  belongs_to :vessel
  belongs_to :sea_state
  belongs_to :cloud_cover
  belongs_to :mode
  belongs_to :species

  has_many :biopsies
  has_many :feces
  has_many :blows
  has_many :animal_sightings
  has_many :animals, through: :animal_sightings

  def self.search(search)
    if search
      where(search.delete_if { |k,v| v.empty? })
    else
      all
    end
  end

  def to_s
    id.to_s
  end
end

app/models/species.rb
class Species < ActiveRecord::Base
  def to_s
    name
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vessel.rb
class Vessel < ActiveRecord::Base
  def to_s
    name
  end
end

app/controllers/animals_controller.rb
class AnimalsController < InheritedResources::Base
  load_and_authorize_resource

  include SmartListing::Scaffold

  def index
    animals = Animal.includes(:species, :vessel).all
    smart_listing_create :animals, animals, partial: "animals/list"
  end

  private

  def columns
    [:number, :field_id, :pics_id, :position_in_group, :biopsy_id,
     :cow_calf, :first_sight, :time, :species_id, :vessel_id]
  end
end

app/controllers/blows_controller.rb
class BlowsController < InheritedResources::Base
  load_and_authorize_resource

  include SmartListing::Scaffold

  belongs_to :sighting

  def index
    smart_listing_create :blows, parent.blows, partial: "list"
  end

  def new
    @blow = Blow.new(sighting: @sighting)
    respond_to do |format|
      format.html { index }
      format.js { super }
    end
  end

  private

  def columns
    [:distance, :quality, :preservation, :behavior, :group_size, :comments,
     :sighting_id]
  end
end

app/controllers/feces_controller.rb
class FecesController < InheritedResources::Base
  load_and_authorize_resource

  include SmartListing::Scaffold

  belongs_to :sighting

  def index
    smart_listing_create :feces, parent.feces, partial: "list"
  end

  def new
    @fece = Fece.new(sighting: @sighting)
    respond_to do |format|
      format.html { index }
      format.js { super }
    end
  end

  private

  def columns
    [:mass, :color, :consistency, :preservation]
  end
end

app/controllers/modes_controller.rb
class ModesController < InheritedResources::Base
  load_and_authorize_resource

  include SmartListing::Scaffold
end

app/controllers/regions_controller.rb
class RegionsController < InheritedResources::Base
  load_and_authorize_resource

  include SmartListing::Scaffold
end

app/controllers/species_controller.rb
class SpeciesController < InheritedResources::Base
  load_and_authorize_resource

  include SmartListing::Scaffold
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_mics_pix(animal:)
    if animal.pics_id.present?
      link_to "MicsPix", MicsPixLinkCreator.new(animal: animal).call,
        target: '_blank'
    end
  end
end

app/views/animals/_form.html.slim
td colspan="12"
  = simple_form_for(object, html: {class: 'form-horizontal' }, remote: true) do |f|
    .container
      .row
        = f.input :number
        = f.input :field_id
        = f.input :pics_id
        = f.input :position_in_group
        = f.association :biopsy
        = f.input :cow_calf
        = f.input :first_sight
        = f.input :time
        = f.association :species
        = f.association :vessel
    .control-group
      .controls
        = f.submit t('shared.submit'), class: 'btn btn-primary'
        button.btn.btn-link.cancel Annuler

app/views/animals/_item.html.slim
td
  = object.number
td
  = object.field_id
td
  = object.pics_id
td
  = object.position_in_group
td
  = object.biopsy
td
  = object.cow_calf
td
  = object.first_sight
td
  = object.time
td
  = object.species
td
  = object.vessel
td
  = link_to_mics_pix(animal: object)
td.actions
  = smart_listing_item_actions [ { name: :edit, url: edit_animal_path(object) },
    { name: :destroy, url: animal_path(object),
      confirmation: t('smart_listing.msgs.destroy_confirmation') }]

app/views/animals/_list.html.slim
h1 Animals
table.table.table-striped
  thead
    td number
    td field_id
    td pics_id
    td position_in_group
    td biopsy
    td cow_calf
    td first_sight
    td time
    td species
    td vessel
    td mixpics
  tbody
    - if smart_listing.empty?
      tr
        td
          = t('smart_listing.no_data')
    - else
      - smart_listing.collection.each do |object|
        tr.editable [data-id="#{object.id}"]
          = render "item", object: object
    = smart_listing.item_new link: new_animal_path
= smart_listing.paginate
= smart_listing.pagination_per_page_links

app/views/animals/index.html.slim
= smart_listing_render(:animals)

app/views/animals/index.js.erb
<%= smart_listing_update :animals %>

app/views/blows/_form.html.slim
td colspan="7"
  = simple_form_for([parent, object],
    html: {class: 'form-horizontal' }, remote: true) do |f|
    .container
      .row
        = f.input :distance
        = f.input :quality
        = f.input :preservation
        = f.input :behavior
        = f.input :group_size
        = f.input :comments
    .control-group
      .controls
        = f.submit t('shared.submit'), class: 'btn btn-primary'
        button.btn.btn-link.cancel Annuler

app/views/blows/_item.html.slim
td
  = object.distance
td
  = object.quality
td
  = object.preservation
td
  = object.behavior
td
  = object.group_size
td
  = object.comments
td.actions
  = smart_listing_item_actions [ { name: :edit, url: edit_sighting_blow_path(parent, object) },
    { name: :destroy, url: sighting_blow_path(parent, object),
      confirmation: t('smart_listing.msgs.destroy_confirmation') }]

app/views/blows/_list.html.slim
h1 Blows
table.table.table-striped
  thead
    th distance
    th quality
    th preservation
    th behaviour
    th group_size
    th comments
    th
  tbody
    - if smart_listing.empty?
      tr
        td
          = t('smart_listing.no_data')
    - else
      - smart_listing.collection.each do |object|
        tr.editable [data-id="#{object.id}"]
          = render "item", object: object
    = smart_listing.item_new link: new_sighting_blow_path
= smart_listing.paginate
= smart_listing.pagination_per_page_links

app/views/blows/index.html.slim
= smart_listing_render(:blows)

app/views/blows/index.js.erb
<%= smart_listing_update :blows %>

app/views/blows/new.html.slim
= smart_listing_render(:blows)
javascript:
  var smart_listing = $('#blows').smart_listing();
  smart_listing.new_item("#{j(render('form', object: resource))}");

app/views/feces/_form.html.slim
td colspan="7"
  = simple_form_for([parent, object],
    html: {class: 'form-horizontal' }, remote: true) do |f|
    .container
      .row
        = f.input :mass
        = f.input :color
        = f.input :consistency
        = f.input :preservation
    .control-group
      .controls
        = f.submit t('shared.submit'), class: 'btn btn-primary'
        button.btn.btn-link.cancel Annuler

app/views/feces/_item.html.slim
td
  = object.mass
td
  = object.color
td
  = object.consistency
td
  = object.preservation
td.actions
  = smart_listing_item_actions [ { name: :edit, url: edit_sighting_fece_path(parent, object) },
    { name: :destroy, url: sighting_fece_path(parent, object),
      confirmation: t('smart_listing.msgs.destroy_confirmation') }]

app/views/feces/_list.html.slim
h1 Feces
table.table.table-striped
  thead
    th mass
    th color
    th consistency
    th preservation
    th
  tbody
    - if smart_listing.empty?
      tr
        td
          = t('smart_listing.no_data')
    - else
      - smart_listing.collection.each do |object|
        tr.editable [data-id="#{object.id}"]
          = render "item", object: object
    = smart_listing.item_new link: new_sighting_blow_path
= smart_listing.paginate
= smart_listing.pagination_per_page_links

app/views/feces/index.html.slim
= smart_listing_render(:feces)

app/views/feces/index.js.erb
<%= smart_listing_update :blows %>

app/views/feces/new.html.slim
= smart_listing_render(:feces)
javascript:
  var smart_listing = $('#feces').smart_listing();
  smart_listing.new_item("#{j(render('form', object: resource))}");

app/views/modes/_form.html.slim
td colspan="2"
  = simple_form_for(object, html: {class: 'form-horizontal' }, remote: true) do |f|
    .container
      .row
        = f.input :name
    .control-group
      .controls
        = f.submit t('shared.submit'), class: 'btn btn-primary'
        button.btn.btn-link.cancel Annuler

app/views/modes/_item.html.slim
td
  = object.name
td.actions
  = smart_listing_item_actions [ { name: :edit, url: edit_mode_path(object) },
    { name: :destroy, url: mode_path(object),
      confirmation: t('smart_listing.msgs.destroy_confirmation') }]

app/views/modes/_list.html.slim
h1 Modes
table.table.table-striped
  thead
    th name
    th
  tbody
    - if smart_listing.empty?
      tr
        td
          = t('smart_listing.no_data')
    - else
      - smart_listing.collection.each do |object|
        tr.editable [data-id="#{object.id}"]
          = render "item", object: object
    = smart_listing.item_new link: new_mode_path
= smart_listing.paginate
= smart_listing.pagination_per_page_links

app/views/modes/index.html.slim
= smart_listing_render(:modes)

app/views/modes/index.js.erb
<%= smart_listing_update :modes %>